site_name: Crystr Documentation
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.footer

markdown_extensions:
  - codehilite
  - toc:
      permalink: true
  - admonition

nav:
  - Home: index.md
  - Getting Started:
      - Hold the Text via StringPack: start/holdthetext.md
      - Using Cry Suffix: start/crysuffix.md
      - Creating Engine: start/createengine.md
      - Finally Encrypting The Text: start/encryptthetext.md
  - API Reference:
      - Engine: api/engine.md
      - Worker: api/worker.md
      - StringPack: api/stringpack.md

extra_css:
  - stylesheets/extra.css
